SET FOREIGN_KEY_CHECKS = 0;
TRUNCATE TABLE attachment;
TRUNCATE TABLE contract;
TRUNCATE TABLE contract_attachments;
TRUNCATE TABLE contract_extra_parameter;
TRUNCATE TABLE contract_stakeholders;
TRUNCATE TABLE land_lease_contract;
TRUNCATE TABLE land_lease_contract_leasehold_additional_information;
TRUNCATE TABLE land_lease_contract_property_designations;
TRUNCATE TABLE stakeholder;
TRUNCATE TABLE stakeholder_roles;
SET FOREIGN_KEY_CHECKS = 1;
