package se.sundsvall.contract.model.enums;

public enum StakeholderRole {
	BUYER,
	CONTACT_PERSON,
	GRANTOR,
	LAND_RIGHT_OWNER,
	LEASEHOLDER,
	PROPERTY_OWNER,
	POWER_OF_ATTORNEY_CHECK,
	POWER_OF_ATTORNEY_ROLE,
	SELLER,
	SIGNATORY
}
